#!/bin/sh

uci -q get local_microservice.settings.url >/dev/null || {
	uci -q add local_microservice settings >/dev/null
	uci -q set local_microservice.settings.url="http://127.0.0.1:9999" >/dev/null
	uci commit local_microservice
}

exit 0
